#+title: Org-remark User Manual
#+author: Noboru Ota <me@nobiot.com>
#+macro: version 0.2.x
#+macro: modified 29 January 2022
#+language: en
#+export_file_name: org-remark.texi
#+texinfo_dir_category: Emacs
#+texinfo_dir_title: Org-remark: (org-remark)
#+texinfo_dir_desc: Highlight and annotate any text file
#+texinfo: @paragraphindent asis
#+options: toc:nil ':t

#+ATTR_TEXINFO: :tag CAUTION
#+begin_quote
This manual is still in a draft version.
#+end_quote

This manual is for Org-remark version {{{version}}}.

Last updated: {{{modified}}}.

Org-remark lets you highlight and annotate any text file with using Org mode.

#+texinfo: @insertcopying

* COPYING
:PROPERTIES:
:COPYING: t
:END:

Copyright \copy 2021-2022  Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below.  A copy of the license is
included in the section entitled “GNU Free Documentation License.”

(a) The FSF’s Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

* Installation
:PROPERTIES:
:CUSTOM_ID: installation
:END:

This package is not available on ELPA or MELPA yet. Manual installation is required.

Ensure to have Org Mode 9.4 or later (tested on 9.4.2). This package uses ~org-collect-keywords~, which does not exist in an earlier version.

Store all the ~.el~ files in the repo in your load-path and put this in your
init file:

#+begin_src emacs-lisp
  ;; Set `load-path' , load `org-remark-global-tracking', and turn it on for
  ;; automatic loading of highlights for the files tracked
  (add-to-list 'load-path "~/local-repos/org-remark")
  (require 'org-remark-global-tracking)
  (org-remark-global-tracking-mode +1)
#+end_src

Unless you explicitly load ~org~ during Emacs initialization, I suggest to defer loading ~org-remark~ (thus there is no ~(require 'org-remark)~ in the example above). This is because it will also pull in ~org~, which can slow down initialization. You can control the timing of loading ~org-remark~ by autoloading some commands in a similar way with the example keybindings below.

Below are example keybindings you might like to consider:

#+begin_src emacs-lisp
  ;; Key-bind `org-remark-mark' to global-map so that you can call it globally
  ;; before the library is loaded.  In order to make `org-remark-mark' and
  ;; `org-remark-mode' callable, use `autoload'.
  (autoload #'org-remark-mark "org-remark" nil t)
  (autoload #'org-remark-mode "org-remark" nil t)
  (define-key global-map (kbd "C-c n m") #'org-remark-mark)

  ;; The rest of keybidings are done only on loading `org-remark'
  (with-eval-after-load 'org-remark
    (define-key org-remark-mode-map (kbd "C-c n o") #'org-remark-open)
    (define-key org-remark-mode-map (kbd "C-c n ]") #'org-remark-view-next)
    (define-key org-remark-mode-map (kbd "C-c n [") #'org-remark-view-prev)
    (define-key org-remark-mode-map (kbd "C-c n r") #'org-remark-remove))
#+end_src

* Getting Started
:PROPERTIES:
:CUSTOM_ID: getting-started
:END:

** Highlighting and Annotating

#+findex: org-remark-mark
#+findex: org-remark-open
#+findex: org-remark-view
#+cindex: Marginal notes file

Once you have installed and set it up ([[#installation][Installation]]), Org-remark is simple to use. Select a part of text and call ~M-x org-remark-mark~ to highlight it. You will see the selected text gets highlighted.

The menu bar item "Org-remark" is available when you turn on ~org-remark-mode~. It helps you discover Org-remark's main commands. If you use Emacs version 28 or newer, a context menu is also available by right click of your mouse. Turn on the Emacs built-in ~context-menu-mode~ to enable the context menu.

To display the marginal notes for the highlight you have just marked, place your cursor on the highlight and call ~M-x org-remark-open~ or ~M-x org-remark-view~. This will display a new buffer to the left of the current buffer you are editing. The ~open~ command takes the cursor to the marginal notes buffer for you to edit notes; whereas the ~view~ command keeps the cursor in the current buffer only to display the marginal notes. Both commands narrow the *marginal notes file* to the entry for the highlight under the cursor.  The marginal notes file is a normal Org file. Edit your notes just as you would do with any other Org files and save the buffer.

** Navigating from One Highlight to Another

#+findex: org-remark-view-next
#+findex: org-remark-view-prev
#+cindex: Menu in the menu bar
#+cindex: Context menu

After you have added a couple of highlights in the text, you can move through the highlights easily. Use ~org-remark-view-next~ and ~org-remark-view-prev~ to browse the marginal notes as you move from one highlight to another. They display the marginal notes on the side-window. Or use ~org-remark-next~ and ~org-remark-prev~ if you simply move to though highlights without displaying marginal notes for them.

To make it easy for you to navigate, you can use the same "prefix key" to Org-remark commands, like this:

- ~C-c n o~: ~org-remark-open~
- ~C-c n ]~: ~org-remark-view-next~
- ~C-c n [~: ~org-remark-view-prev~
- ~C-c n r~: ~org-remark-remove~

The ~C-c n~ are the prefix key common to all of them. If you set the keybindings like this, you can use ~C-c n ]~ once to view the next highlight and simply keep using a single key ~]~ or ~[~ to browse the next/previous highlights. After you have reached the one you like to act on, press ~o~ to open it, or ~r~ to remove it.

** Create Your Own Highlighter Pens

#+cindex: Custom highlighter pens

Org-remark has a default highlighter pen function, and comes with a set of two additional pens by default:

- ~org-remark-mark~           :: default highlighter pen
- ~org-remark-mark-yellow~    :: yellow highlight with "important" category in the marginal notes entry
- ~org-remark-mark-red-line~  :: wavy red underline with "review" category in the marginal notes entry and "Review this" in tool-tips

Org-remark let lets you create your own custom pen functions with ~org-remark-create~. Use the yellow and red line pens as examples, and create your own. For how to do it, [[#create-custom-pens][How to Create Custom Highlighter Pens]].

This is all you need to get started. For more detail, refer to the rest of this user manual, especially [[#usage][Usage]] and [[#customizing][Customizing]] sections. There is more to the commands introduced in this section and more ways in which you can customize Org-remark. 

* Usage
:PROPERTIES:
:CUSTOM_ID: usage
:END:

** How to Create Custom Highlighter Pens
:PROPERTIES:
:CUSTOM_ID: create-custom-pens
:END:

#+cindex: Custom highlighter pens
#+cindex: Org-remark properties for highlights
#+findex: org-remark-mark
#+findex: org-remark-mark-yellow
#+findex: org-remark-mark-red-line
#+findex: org-remark-create

~org-remark-create~ is a macro that lets create your own custom pen functions. Org-remark comes with two additional pens that are created by default. Use them as examples to learn how to create your own.

#+begin_src elisp
  (org-remark-create "red-line"
                     '(:underline (:color "dark red" :style wave))
                     '(CATEGORY "review" help-echo "Review this"))
  (org-remark-create "yellow"
                     '(:underline "gold" :background "lemon chiffon")
                     '(CATEGORY "important"))
#+end_src

- Macro: ~org-remark-create~ label &optional face properties ::
  Create and register new highlighter pen functions. The newly created pen function will be registered to variable ~org-remark-available-pens~.  It is used by ~org-remark-change~ as a selection list.

  LABEL is the name of the highlighter and mandatory.  The function will be named ~org-remark-mark-LABEL~.

  The highlighter pen function will apply FACE to the selected region. FACE can be an anonymous face.  When FACE is nil, this macro uses the default face ~org-remark-highlighter~.

  PROPERTIES is a plist of pairs of a symbol and value. Each highlighted text region will have a corresponding Org headline in the notes file, and it can have additional properties in the property drawer from the highlighter pen.  To do this, prefix property names with "=org-remark-=" or use "=CATEGORY=".

#+ATTR_TEXINFO: :tag NOTE
#+begin_quote
Don't use =category= (all lowercase, symbol) as a property -- it's a special one for text properties. If you use it, the value also need to be a symbol; otherwise, you will get an error. You can use =CATEGORY= (all uppercase, symbol), which will result in adding =CATEGORY= with the value in the property drawer in marginal notes Org files.
#+end_quote

** Automatically Turn on Highlights after Re-starting Emacs

#+findex: org-remark-global-tracking-mode
#+findex: org-remark-mode
#+vindex: org-remark-tracking-file

It is recommended that ~org-remark-global-tracking-mode~ be turned on as part of your Emacs initialization. This should be done before you start adding highlights in any file. 

Once you have added highlights to some files, quit Emacs, and re-start it, active ~org-remark-global-tracking-mode~ will automatically turn on ~org-remark-mode~ and load the highlights from your previous sessions for the files being globally tracked.

When activated, ~org-remark-global-tracking-mode~ will also start remembering and tracking the files to which you add highlights and annotations. When you quit Emacs, it will save the tracked files in a file in your Emacs config directory (~user-emacs-directory~). By default, this file is named ~.org-remark-tracking~ ([[#customizing][Customizing]]).

Without this global minor mode, you would need to remember to activate ~org-remark-mode~ for each file where you add highlights and annotation. This is often unpractical. 

** Marginal Notes File

#+cindex: Marginal notes file
#+cindex: Org-remark properties for highlights

When you mark a part of text with a highlighter pen function, Org-remark will automatically create a *marginal notes file*. By default, it will be named ~marginalia.org~ and created in the same directory as the file you are editing ([[#customizing][Customizing]]).

The important thing to note is that Org-remark uses following properties in the property drawer of the headline to remember the highlights:

- :org-remark-beg:
- :org-remark-end:
- :org-remark-id:
- :org-remark-label:

Essentially, the marginal notes file is a database in the plain text with using Org mode. As a plain text database, you can easily edit these properties manually if necessary.

You can leave the marginal notes file as it is without writing any notes. In this case, the entries in marginal notes file simply save the locations of your highlighted text. After you quit Emacs,  re-start it, and visit the same main file, Org-remark uses this information to highlight the text again. You can also directly edit the marginal notes file as a normal Org file.

In addition to the properties above that Org-remark reserves for itself, you can add your own custom properties and ~CATEGORY~ property. Use "org-remark-" as the prefix to the property names (or "CATEGORY", which is the only exception), and Org-remark put them to the property drawer of highlight's headline entry in the marginal notes buffer. Define the custom properties in your own custom pen functions (for how to create your own pens, [[#create-custom-pens][How to Create Custom Highlighter Pens]]). 

** =*marginal-notes*= Buffer

#+cindex: *marginal notes* buffer

When you display the marginal notes with ~org-remark-view~ or ~org-remark-open~ for a given highlight, Org-remark creates a cloned indirect buffer visiting the marginal notes file. By default, it is a dedicated side-window opened to the left part of the current frame, and it is named =*marginal notes*=. You can change the behavior of ~display-buffer~ function and the name of the buffer ([[#customizing][Customizing]]).

Org-remark displays the marginal notes buffer narrowed to the highlight the cursor is on. 

** Other Commands

#+findex: org-remark-toggle
#+findex: org-remark-change
#+findex: org-remark-remove
#+findex: org-remark-delete
#+findex: org-remark-next
#+findex: org-remark-prev

- Command ~org-remark-toggle~ ::
  Toggle showing/hiding of highlights in current buffer.
  If you would like to hide/show the highlights in the current buffer, it is recommended to use this command instead of ~org-remark-mode~. This command only affects the display of the highlights and their locations are still kept tracked.  Toggling off ~org-remark-mode~ stops this tracking completely, which will likely result in inconsistency between the marginal notes file and the current main buffer.

- Command ~org-remark-change~ ::
  Change the highlight at point to one by another pen. This command will show you a list of available pens to choose from.

- Command ~org-remark-remove~ ::
  Remove the highlight at point.
  It will remove the highlight and the properties from the marginal notes file, but will keep the headline and annotations. This is to ensure to keep any notes you might have written intact.
  You can let this command DELETE the entire heading subtree for the highlight along with the annotations you have written, by passing a universal argument with ~C-u~. If you have done so by error, you could still ~undo~ it in the marginal notes buffer, but not from within the current buffer as adding and removing overlays are not part of the undo tree.

- Command ~org-remark-delete~ ::
  Delete the highlight at POINT and marginal notes for it.
  This function will prompt for confirmation if there is any notes present in the marginal notes buffer.  When the marginal notes buffer is not displayed in the current frame, it will be temporarily displayed together with the prompt for the user to see the notes.
  If there is no notes, this function will not prompt for confirmation and will remove the highlight and deletes the entry in the marginal notes buffer. This command is identical with passing a universal argument to `org-remark-remove'.

To navigate through highlights in the current buffer, you can use ~org-remark-view-next~ / ~org-remark-view-prev~ or the following pair of commands. The former moves your cursor and displays the marginal notes buffer; the latter only moves your cursor.

- Command ~org-remark-next~ ::
  Move to the next highlight, if any.
  If there is none below the point but there is a highlight in the buffer, cycle back to the first one.
  After the point has moved to the next highlight, this command lets you move further by re-entering only the last letter like this example:  =C-n ] ] ] ] ]= (assuming this command is bound to C-n ])

- Command ~org-remark-prev~ ::
  Move to the previous highlight, if any.

* Customizing
:PROPERTIES:
:CUSTOM_ID: customizing
:END:

#+vindex: org-remark-highlighter
#+vindex: org-remark-create-default-pen-set
#+vindex: org-remark-notes-file-path
#+vindex: org-remark-notes-display-buffer-action
#+vindex: org-remark-notes-buffer-name
#+vindex: org-remark-use-org-id
#+vindex: org-remark-tracking-file

Org-remark's user options are available in the customization group ~org-remark~.

- Face: ~org-remark-highlighter~ ::
  Default face for ~org-remark-mark~

- Option: ~org-remark-create-default-pen-set~ ::
  When non-nil, Org-remark creates default pen set. Set to nil if you prefer for it not to.
  
- Option: ~org-remark-notes-file-path~ ::
  Define the file path to store the location of highlights and write annotations.
  The default is one file per directory. Ensure that it is an Org file.

- Option: ~org-remark-notes-display-buffer-action~ ::
  Define how Org-remark opens the notes buffer.
  The default is to use a dedicated side-window on the left. It is an action list for ~display-buffer~. Refer to its documentation for more detail and expected elements of the list.

- Option: ~org-remark-notes-buffer-name~ ::
  Define the buffer name of the marginal notes.
  ~org-remark-open~ creates an indirect clone buffer with this name.

- Option: ~org-remark-use-org-id~ ::
  Define if Org-remark use Org-ID to link back to the main note.

- Option: ~org-remark-tracking-file~ ::
  Define file path to save the files ~org-remark~ tracks.
  When ~org-remark-global-tracking-mode~ is active, opening a file saved in
 ~org-remark-tracking-file~ automatically loads highlights.

* Known Limitations

- No export together with the main file :: There is no out-of-the-box feature to export marginal notes together with the main file.  Nevertheless, the marginal notes is a normal Org file, thus if the main file is also an Org file, you could use the built-in =include= feature, for example, to include relevant parts of the marginal notes into the export output.

- Copy & pasting loses highlights :: Overlays are not part of the kill; thus cannot be yanked.
  
- Undo highlight does not undo it :: Overlays are not part of the undo list; you cannot undo highlighting. Use ~org-remark-remove~ command instead.
  
- Moving source files and remark file :: Move your files and remark file to another directory does not update the source path recorded in the remark file. It will be confusing. Try not to do it.

- Marginal notes file uses absolute path :: Related to the previous limitation. The marginal notes file serves as the database for the highlights' locations and notes. The linkage back to the main note files are via absolute paths.  This means moving files to a different path is likely to break the the links.

* Credits

To create this package, I was inspired by the following packages. I did not copy any part of them, but borrowed some ideas from them -- e.g. saving the margin notes in a separate file.

- [[https://github.com/jkitchin/ov-highlight][Ov-highlight]] :: John Kitchin's (author of Org-ref). Great UX for markers with hydra. Saves the marker info and comments directly within the Org file as Base64 encoded string. It uses overlays with using ~ov~ package.
  
- [[https://github.com/bastibe/annotate.el][Annotate.el]] :: Bastian Bechtold's (author of Org-journal). Unique display of annotations right next to (or on top of) the text. It seems to be designed for very short annotations, and perhaps for code review (programming practice); I have seen recent issues reported when used with variable-pitch fonts (prose).
  
- [[https://github.com/tkf/org-mode/blob/master/contrib/lisp/org-annotate-file.el][Org-annotate-file]] :: Part of Org's contrib library. It seems to be designed to annotate a whole file in a separate Org file, rather than specific text items.
  
- [[https://github.com/IdoMagal/ipa.el][InPlaceAnnotations (ipa-mode)]] :: It looks similar to Annotate.el above.
  
- Transient navigation feature :: To implement the transient navigation feature, I liberally copied the relevant code from a wonderful Emacs package, [[https://github.com/rnkn/binder/blob/24d55db236fea2b405d4bdc69b4c33d0f066059c/binder.el#L658-L665][Binder]] by Paul W. Rankin (GitHub user [[https://github.com/rnkn][rnkn]]). 

* Contributing & Feedback

Create issues, discussion, and/or pull requests in the GitHub repository. All welcome.

Org-remark is planned to be submitted to GNU ELPA and thus copyrighted by the [[http://fsf.org][Free Software Foundation]] (FSF). This means that anyone who is making a substantive code contribution will need to "assign the copyright for your contributions to the FSF so that they can be included in GNU Emacs" ([[https://orgmode.org/contribute.html#copyright][Org Mode website]]).

Thank you.

* Index - Features
:PROPERTIES:
:CUSTOM_ID: cindex
:APPENDIX: t
:INDEX:    cp
:DESCRIPTION: Key concepts & features
:END:

* Index - Commands
:PROPERTIES:
:APPENDIX: t
:INDEX:    fn
:DESCRIPTION: Interactive functions
:END:

* Index - User Options
:PROPERTIES:
:APPENDIX: t
:INDEX:    vr
:DESCRIPTION: Customizable variables & faces
:END:

* GNU Free Documentation License
:PROPERTIES:
:appendix: t
:END:

#+texinfo: @include fdl.texi

# Local Variables:
# time-stamp-start: "modified +\\\\?"
# End:
