#+title: Org-remark User Manual
#+author: Noboru Ota <me@nobiot.com>
#+macro: version 0.0.7
#+macro: modified 03 January 2022

#+language: en
#+export_file_name: org-remark.texi
#+texinfo_dir_category: Emacs
#+texinfo_dir_title: Org-remark: (org-remark)
#+texinfo_dir_desc: Highlight and annotate any text file
#+texinfo: @paragraphindent asis

#+options: toc:nil ':t

#+ATTR_TEXINFO: :tag CAUTION
#+begin_quote
This manual is still in a draft version and missing some key information relevant to the version being described.
#+end_quote

This manual is for Org-remark version {{{version}}}.

Last updated: {{{modified}}}.

Org-remark lets you highlight and annote any text file with using Org mode.

#+texinfo: @insertcopying

* COPYING
:PROPERTIES:
:COPYING: t
:END:

Copyright (C) 2021  Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below.  A copy of the license is
included in the section entitled “GNU Free Documentation License.”

(a) The FSF’s Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

* Installation
:PROPERTIES:
:TOC:      :depth 0
:END:

** Manual

This package is not available on ELPA or MELPA yet. Manual installation is required.

Ensure to have Org Mode 9.4 or later (tested on 9.4.2). This package uses ~org-collect-keywords~, which does not exist in an earlier version.

Store both of the =.el= files in the repo in your load-path, and put this in your init file:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/local-repos/org-remark/")
  (require 'org-remark-global-tracking)
  (require 'org-remark)
#+END_SRC

By loading =org-remark=, it will also pull in Org mode. You might like to defer loading of Org as it might take long time. As of version 0.0.6, you can do so with loading only =org-remark-global-tracking=, which does not load =org= automatically.

For example, I use this in my init file. 

#+begin_src emacs-lisp
  ;; Set `load-path'
  (add-to-list 'load-path "~/local-repos/org-remark")

  ;; Load only `org-remark-global-tracking'
  ;; and turn it on for automatic loading of highlights
  ;; for the files tracked
  (load-library "org-remark-global-tracking")
  (org-remark-global-tracking-mode 1)

  ;; Set keybindings `org-remark-mark' is bound to global-map so that you can
  ;; call it globally before the library is loaded.  In order to make
  ;; `org-remark-mark' and `org-remark-mode' callable, use `autoload'.
  ;; When this package is available in MELPA, `autoload' should not be required.
  (autoload #'org-remark-mark "org-remark" nil t)
  (autoload #'org-remark-mode "org-remark" nil t)
  (define-key global-map (kbd "C-c n m") #'org-remark-mark)
  ;; The rest of keybidings are done only on loading `org-remark'
  (with-eval-after-load 'org-remark
    (define-key org-remark-mode-map (kbd "C-c n o") #'org-remark-open)
    (define-key org-remark-mode-map (kbd "C-c n ]") #'org-remark-next)
    (define-key org-remark-mode-map (kbd "C-c n [") #'org-remark-prev)
    (define-key org-remark-mode-map (kbd "C-c n r") #'org-remark-remove))
#+end_src
  
* Getting Started

To be added

* Usage
:PROPERTIES:
:TOC:      :depth 0
:END:
** Commands

- =org-remark-global-tracking-mode= ::
A global minor mode to save and track files that have marginal notes.
When active, visiting a file being tracked automatically turns on =org-remark-mode=, which loads highlights previously saved in the remark file.

The files being tracked are saved in =org-remark-tracking-file=, which you can customize. The default file is named =.org-remark-tracking= in your Emacs configuration directory (=user-emacs-directory=).

- =org-remark-mode= ::
Org-remark is a local minor mode. Toggle it on/off with using =org-remark-mode=. On activating, it loads your saved highlights from the remark file (defined by =org-remark-notes-file-path=), and enables automatic saving of highlights. The automatic saving is achieved via function =org-remark-save= added to =after-save-hook=.

- =org-remark-mark= ::
Select a region of text, and call =org-remark-mark= to highlight the region. It will generate a new ID, and start tracking the location -- so you can edit text around the highlighted text. Do not cut, copy and paste as the highlight will disappear (you can immediately =undo= to recover the text region along the highlights). To create a new marginal note entry in the remark file, save the buffer.

- =org-remark-save= ::
By default, Org-remark automatically creates or updates corresponding entries in the remark file with location and text of highlights on saving the buffer. Nevertheless, you can manually call =org-remark-save= to do so (automatic process also call this command).

If user option =org-remark-use-org-id= is non-nil, Org-remark will
create a link back to the source note with using an Org-ID link instead of a
normal file link.

When a new remark file is created and =org-remark-use-org-id= is
non-nil, Org-remark will add an ID property to the file level. This is mainly to support Org-roam's backlink feature for remark files.

- =org-remark-open= ::
Move your cursor on the highlighted text, and call =org-remark-open= to open the relevant margin notes in a separate window. Your cursor will move to the remark buffer narrowed to the relevant margin notes entry. You can edit the remark buffer as a normal Org buffer. Once you have done editing, you may simply save and close the it (kill it or close the window) as per your normal workflow. Technically, the remark buffer is a cloned indirect buffer of the remark file. 

- =org-remark-load= ::
This command visits the remark file and loads the saved highlights onto the current buffer. If there is no margin notes for it, it will output a message in the echo. Highlights tracked locally by Org-remark cannot persist when you kill the buffer, or quit Emacs. When you re-launch Emacs, ensure to turn on =org-remark-mode= to load the highlights. Loading is automatically done when you activate the minor mode.

- =org-remark-remove= ::
This command removes the highlight at point. It will remove the highlight, and remove the properties from the remark, but will keep the headline and notes in tact.

You can pass a universal argument (=C-u= by default). If this is the case, the command additionally deletes the entire heading subtree, along with the notes you have written, for the highlight.

- =org-remark-next= ::
Move to the next highlight if any. If there is none below the cursor, and there is a highlight above, loop back to the top one.
If the point has moved to the next highlight, this function enables transient map with `set-transient-map'. You don't have to press the keybinding prefix again to move further to the next. That is, you can do a key sequence like this:

   =C-c n ] ] ] ]=

If you have the same prefix for `org-remark-prev', you can combine it in
the sequence like so:

  =C-c n ] ] [ [=
  This lets your cursor back to where you started (next next prev prev)

- =org-remark-prev= ::
Move to the previous highlight if any. If there is none above the cursor, and there is a highlight below, loop back to the bottom one. This function enables transient map. See =org-remark-next= for detail.

- =org-remark-toggle= ::
Toggle showing/hiding of highlighters in current buffer. It only affects the display of the highlighters. When hidden, highlights' locations are still kept tracked; thus, upon buffer-save the correct locations are still recorded in the remark file.

** Keybindings Examples

`Org-remark` only provides its mode map, and does not bind any keys to it. As an example, you could do something like this below.

#+begin_src emacs-lisp
(define-key org-remark-mode-map (kbd "C-c n o") #'org-remark-open)
(define-key org-remark-mode-map (kbd "C-c m") #'org-remark-mark)
(define-key org-remark-mode-map (kbd "C-c n ]") #'org-remark-next)
(define-key org-remark-mode-map (kbd "C-c n [") #'org-remark-prev)
#+end_src

** Composing Personal Workflow

Currently only "elementary" functions are defined in the package; for example,  =mark= , =save=, and =open= are all separate functions. You can string these together to compose a more fluid operation to suite your own workflow. A very useful set of such chained commands have been suggesetd by holtzermann17 in [[https://org-roam.discourse.group/t/prototype-org-remark-write-margin-notes-with-org-mode/1080/10][Org-roam's Discourse discussion]] (adjusted to reflect the change of the prefix from =om/= to =org-remark-=) .

I will try to incorporate these into the package when I have more time to focus on it -- I find them useful, but there are some plans I have had, and want to think of how I can incoprate these suggestions better with my ideas. 

#+begin_src emacs-lisp
  (defun org-remark-make-annotation ()
    (interactive)
    (let ((mark-end (region-end)))
      (org-remark-mark (region-beginning) (region-end))
      (org-remark-save)
      (org-remark-open (1- mark-end))
      (end-of-buffer)))

  (define-key org-remark-mode-map (kbd "C-c M")
    #'org-remark-make-annotation)

  (defun org-remark-browse-forward ()
    (interactive)
    (let ((buf (current-buffer)))
      (org-remark-next) (org-remark-open (point))
      (pop-to-buffer buf nil t)))

  (define-key org-remark-mode-map (kbd "C-c n }")
    #'org-remark-browse-forward)

  (defun org-remark-browse-backward ()
    (interactive)
    (let ((buf (current-buffer)))
      (org-remark-prev) (org-remark-open (point))
      (pop-to-buffer buf nil t)))

  (define-key org-remark-mode-map (kbd "C-c n {")
    #'org-remark-browse-backward)
#+end_src

* Customizing

- You can customize settings in the =org-remark= group.
- Highlight's face can be changed via =org-remark-highlighter=
- Remark file is defined by =org-remark-notes-file-path=
- Your files with marginal notes are saved and tracked in
  =org-remark-tracking-file= (when tracking is turned on via the global
  minor mode =org-remark-global-tracking-mode=)
- You can use Org-ID to create links from marginal notes back to their main
  notes when =org-remark-use-org-id= is on (default is on). This option also enables Org-remark to add an ID property when a new remark file is being created. This is to support seamless workflow with [[https://orgroam.com][Org-roam]].

* Known Limitations

- Copy & pasting loses highlights :: Overlays are not part of the kill; thus cannot be yanked.
  
- Undo highlight does not undo it :: Overlays are not part of the undo list; you cannot undo highlighting. Use =org-remark-remove= command instead.
  
- Moving source files and remark file :: Move your files and remark file to another directory does not update the source path recorded in the remark file. It will be confusing. Try not to do this.

* Credits

To create this package, I was inspired by the following packages. I did not copy any part of them, but borrowed some ideas from them -- e.g. saving the margin notes in a separate file.

- [[https://github.com/jkitchin/ov-highlight][Ov-highlight]] :: John Kitchin's (author of Org-ref). Great UX for markers with hydra. Saves the marker info and comments directly within the Org file as Base64 encoded string. It uses overlays with using `ov` package.
  
- [[https://github.com/bastibe/annotate.el][Annotate.el]] :: Bastian Bechtold's (author of Org-journal). Unique display of annotations right next to (or on top of) the text. It seems to be designed for very short annotations, and perhaps for code review (programming practice); I have seen recent issues reported when used with variable-pitch fonts (prose).
  
- [[https://github.com/tkf/org-mode/blob/master/contrib/lisp/org-annotate-file.el][Org-annotate-file]] :: Part of Org's contrib library. It seems to be designed to annotate a whole file in a separate Org file, rather than specific text items.
  
- [[https://github.com/IdoMagal/ipa.el][InPlaceAnnotations (ipa-mode)]] :: It looks similar to Annotate.el above.
  
- Transient navigation feature :: To implement the transient navigation feature, I liberally copied the relevant code from a wonderful Emacs package, [[https://github.com/rnkn/binder/blob/24d55db236fea2b405d4bdc69b4c33d0f066059c/binder.el#L658-L665][Binder]] by Paul W. Rankin (GitHub user [[https://github.com/rnkn][rnkn]]). 

* Feedback

Feedback welcome in this repo, or in [[https://org-roam.discourse.group/t/prototype-org-marginalia-write-margin-notes-with-org-mode/1080][Org-roam Discourse forum]]. 

* Contributing

To be added

* Index - Features
:PROPERTIES:
:CUSTOM_ID: cindex
:APPENDIX: t
:INDEX:    cp
:DESCRIPTION: Key concepts & features
:END:

* Index - Commands
:PROPERTIES:
:APPENDIX: t
:INDEX:    fn
:DESCRIPTION: Interactive functions
:END:

* Index - User Options
:PROPERTIES:
:APPENDIX: t
:INDEX:    vr
:DESCRIPTION: Customizable variables & faces
:END:

* GNU Free Documentation License
:PROPERTIES:
:appendix: t
:END:

#+texinfo: @include fdl.texi

# Local Variables:
# time-stamp-start: "modified +\\\\?"
# End:
